### ISSUE TITLE
jpar files

### ISSUE THREAD

**Issue by fr4ncidir** [arces-wot/SEPA#23]
We should put them in .gitignore?
In any case, I think they should be downloaded when cloning the repo, but modifications should be not checked.

**Comment by relu91** [comment]
Yes I think they should be ignored. This way the jpar files that are already in the repository will be still downloaded, but we wouldn't be able to create new one or change the default one. 

Maybe we could put them in a folder as an example or as reference documentation and ignore all the .jpar outside that location. What do you think?

**Comment by lroffia** [comment]
From version 0.9.0 the broker creates the defaults engine.jpar and endpoint.jpar (the latter uses the online instance of Virtuoso at mml.arces.unibo.it). Configurations for other endpoints can be provided in other ways (folders, readme, ...),
