### ISSUE TITLE
SPARQL11SEProtocol NPE on subscribe

### ISSUE THREAD

**Issue by relu91** [arces-wot/SEPA#27]
Using _SPARQL11SEProtocol_ with default constructor can cause a _NullPointerException_ when subscribe method is called.

**How to riproduce**
 ```java
final SPARQL11SEProperties properties = new SPARQL11SEProperties(new File("file.jsap"));
client = new SPARQL11SEProtocol(properties);

SubscribeRequest sub = new SubscribeRequest("select * where {?a ?b ?c}");
client.subscribe(sub); //NPE
```
**Cause**
The `SPARQL11SEProtocol(properties)` constructor doesn't initialize the _wsClient_ with an instance of _SPARQL11SEWebsocket._ This probably was to done to avoid pointless usage of system resources since the client user would never ricieve any notification because he doesn't specify a _ISubscriptionHandler._
 
**Expected behavior**
The client should use a specific exception to handle this kind of bad api use. Better it shouldn't implement the `SPARQL11SEProtocol(properties)` constructor because if the client wants only to update and query a _SPARQL11Protocol_ instance is more suited.

**Comment by lroffia** [comment]
@relu91 could please try with the new release?

**Comment by relu91** [comment]
I can confirm that in the new release the exception is not thrown.
