### ISSUE TITLE
SEPA 2nd run fails with default .jpar(s)

### ISSUE THREAD

**Issue by fr4ncidir** [arces-wot/SEPA#40]
**Describe the bug**
Error message:
```
[...]
# WEB: http://site.unibo.it/wot                                                          #
# WIKI: https://github.com/arces-wot/SEPA/wiki                                           #
##########################################################################################
2018-10-14T21:02:07,194 [ERROR] [main                     ] (EngineProperties.java:182) scheduler-timeout is missing
null
```

**To Reproduce**
Run 2 times the engine v0.9.5

**Expected behavior**
running normally

**System information(please complete the following information):**
 - OS: Ubuntu 18.04.1 LTS
 - Engine version: 0.9.5
 - SparqlEnpoint used [e.g. blazegraph 1.0.7]: blazegraph 2.1.4

**Additional context**
Deleting .jpars makes the engine run again.

**Comment by relu91** [comment]
Thank you for submitting!

It's seems that the default jpar has some wrong configuration proprieties.

I'll fix it ASAP.

**Comment by lroffia** [comment]
I fixed the bug. Please merge into dev and publish the release

**Comment by relu91** [comment]
Fix released. version 0.9.6
