### ISSUE TITLE
Subscription duplication function

### ISSUE THREAD

**Issue by fr4ncidir** [arces-wot/SEPA#42]
When I subscribe, I get a subscription id.

Let's consider that I have to build up another client, and its task is related to the same sparql subscription.
For now, I just take the same SPARQL and subscribe as I did in the previous.

Why not do something like
```
dup_subid = duplicate_subscription(subid)
```
which adds another client to the ones interested in a pre-existing subscription?

**Comment by relu91** [comment]
I could be wrong but this mechanism should be already implemented in the latest version of the software. Some months ago @lroffia was developing this feature and if I remember correctly he fished the implementation some weeks ago. Anyway, it is a great idea and it helps a lot the scalability of the platform!

**Comment by relu91** [comment]
Have a look at commit 5f68afbcda528eeda4b8df9396791793683f1f61. 😄

**Comment by fr4ncidir** [comment]
I don't think there's an api description for this... Isn't it?

Il giorno ven 30 nov 2018, 12:53 Cristiano Aguzzi <notifications@github.com>
ha scritto:

**Comment by lroffia** [comment]
The matching is performed by the broker. If two SPARQL subscribes are equals (at the moment like sub1.equals(sub2)) they will be managed by the same SPU (one thread). Different clients will have different spuids with different sequence number. So, for a client the mechanism is hidden by the broker.

**Comment by relu91** [comment]
I'll close the issue, the question seems to have been answered.
