### ISSUE TITLE
Forced binding doesn't use the default type

### ISSUE THREAD

**Issue by relu91** [arces-wot/SEPA#49]
**Describe the bug**
When you bind a SPARQL variable to a value in Java API, the APIs ignores the default type stated in JSAP and uses `xsd:string`.

**To Reproduce**
1. Create a JSAP with one update and one forcedBinding with type `xsd:decimal`
2. Set the forced binding using the one argument constructor of `RDFTermLiteral`
3. execute the update
4. check the data type of the value inserted in the DB. 

**Expected behavior**
The dataType should `xsd:decimal` instead `xsd:string` 

**System information(please complete the following information):**
 - OS: Windows
 - Engine version: 0.9.5
 - SparqlEnpoint used blazegraph

**Comment by lroffia** [comment]
Fixed...hopefully ;-)
