### ISSUE TITLE
404 WebSocket Upgrade Failure

### ISSUE THREAD

**Issue by yasirhm** [arces-wot/SEPA#56]
**404 WebSocket Upgrade Failure**
I have built the maven project successfully, However after running the engine, and trying to subscribe, I get the error that 404 WebSocket Upgrade Failure. 

**To Reproduce**
1. SEPA/json-ld
2. mvn clean install 
3. Run engine 
4. go to http://127.0.0.1:9000/
5. See the error

**System information(please complete the following information):**
 - OS: [Ubuntu 18.04.4]
 - Engine version [pulled the sepa/ngsi-ld]
 - SparqlEnpoint used [e.g. blazegraph 2.1.6]

**Additional context**
If there is something that I'm missing, please let me know.

**Comment by lroffia** [comment]
These are the endpoints provided by SEPA:

SPARQL 1.1 Protocol (https://www.w3.org/TR/sparql11-protocol/)
----------------------
SPARQL 1.1 Query     | http://localhost:8000/query
SPARQL 1.1 Update    | http://localhost:8000/update
----------------------

SPARQL 1.1 SE Protocol (http://mml.arces.unibo.it/TR/sparql11-se-protocol.html)
----------------------
SPARQL 1.1 Subscribe | ws://localhost:9000/subscribe
----------------------

So to use subscriptions you should go to the following: **ws://localhost:9000/subscribe**

Also you need a websocket client like the following: **https://github.com/hakobera/Simple-WebSocket-Client**

**Comment by yasirhm** [comment]
Thank you. Issue was in WebSocket.
