### ISSUE TITLE
<help wanted>  Problems about implementing delete function based on NGSI-LD 

### ISSUE THREAD

**Issue by bliu92** [arces-wot/SEPA#63]
Hallo, Happy new year guys.
I have a problem when implementing NGSI-LD protocols upon NGSI-LD. I just clone the NGSI-LD branch directly. The get entity is implemented and i would like to implement a delete function by entity ID.

The delete function is in NsgiLdRdfMapper.java as following:

public boolean deleteEntityById(String entityId) {
                        if (getEntityById(entityId) == null) {
			return false;
		}

		JsonObject jsonld = getEntityById(entityId);

		if (jsonld == null)
			return false;

		RDFDataset ds = fromJsonLd(jsonld);

		if (ds == null | ds.isEmpty())
			return false;

		String triples = nTriples(ds);
		String sparql = "DELETE DATA { GRAPH <" + NgsiLdRdfMapper.ngsiLdEntitiesGraph + "> {" + triples + "}";
		Response ret = update(sparql);

		if (ret.isError()) {
			ErrorResponse error = (ErrorResponse) ret;
			lastError = NgsiLdError.InternalError;
			lastError.setTitle(error.getError());
			lastError.setDetail(error.getErrorDescription());
			return false;
		}

		return true;
	}

And in EntityById.java in handlers folder i declared the delete function:

protected void delete(String link) {
		super.delete(link);

		// Get the entity ID
		String entityId = "";
		entityId = matcher.group("id");

		// Get entity graph
		JsonObject jsonld = ngsiLdRdfMapper.getEntityById(entityId);

		if (jsonld == null) {
			NgsiLdError error = ngsiLdRdfMapper.getLastError();
			setResponse(error.getErrorCode(), "application/json", error.getJsonResponse(), null);
			return;
		}

		if (ngsiLdRdfMapper.deleteEntityById(entityId)) {
			setResponse(204, null, null, null);
		}

	}

When i try to delete the entity i posted using NGSI-LD, there is a java nullpoint exception.
My idea to implement delete is firstly to construct all RDF triples using query about the entity and then using update to delete this entity. The error is always nullpointer exception. Besides, since i don't know how to unit testing in this part.

It would be really nice if you guys could help me to have a look at my codes and may teach me how to unit testing protocols since each time when i build the project, i need to skill all tests, otherwise it failed.

best wishes 
Bang

**Comment by lroffia** [comment]
Dear @bliu92,

thank you so much for the greetings! Happy New Year!

Unfortunately the branch is very old and before proceeding a merge with the current active branch (dev) is needed. At the moment we have no resources to work on this task but we are looking for funding to re-open the NGSI-LD development aiming at implementing the full NGSI-LD API by the end of the year. So I am sorry but at the moment we cannot support you.
