### ISSUE TITLE
General Question about the SPARQL UPDATE using DELETE Function.

### ISSUE THREAD

**Issue by bliu92** [arces-wot/SEPA#64]
**Describe the bug**
DELETE Function not working well

Hallo, I have a general question about the update function in SEPA Dashboard.

DELETE {
  GRAPH <http://uri.etsi.org/ngsi-ld/Entities> {
    <urn:ngsi-ld:Vehicle:V123> <http://uri.fiware.org/ns/datamodels/speed> ?blank.
    ?blank <http://uri.etsi.org/ngsi-ld/hasValue> ?d 
  }
} INSERT {
  GRAPH <http://uri.etsi.org/ngsi-ld/Entities> {
    <urn:ngsi-ld:Vehicle:V123> <http://uri.fiware.org/ns/datamodels/speed> ?blank.
    ?blank <http://uri.etsi.org/ngsi-ld/hasValue> "42"^^<http://www.w3.org/2001/XMLSchema#integer>
  }
}

I use this code in the SEPA Dashboard to test the function of deletion. I would like to replace the original speed value from 23 to 42. I query all the necessary and the name of the graph, and now i would like to change the value. However, there is no changes happen. I subscribe the speed value in the Dashboard as well and there is no notification.

**Expected Values**
After updating, the speed value should change from the original 23 to the new integer value 42. Besides, the subscription of the speed value should provide an notification.

**System information(please complete the following information):**
 - OS: MacOS 11.1
 - Engine version [Version in the NGSI-LD branch]
 - blazegraph 2.1.5

**Comment by lroffia** [comment]
Could you please switch to the master branch. The branch you are using is at the moment deprecated. Please let me know if you still have the problem. What I also notice is that you UPDATE is wrong. Try as follows:

DELETE {
GRAPH **<http://uri.etsi.org/ngsi-ld/Entities>** {
urn:ngsi-ld:Vehicle:V123 **<http://uri.fiware.org/ns/datamodels/speed>** ?blank.
?blank **<http://uri.etsi.org/ngsi-ld/hasValue>** ?d
}
} INSERT {
GRAPH **<http://uri.etsi.org/ngsi-ld/Entities>** {
urn:ngsi-ld:Vehicle:V123 **<http://uri.fiware.org/ns/datamodels/speed>** ?blank.
?blank **<http://uri.etsi.org/ngsi-ld/hasValue>** "42"^^http://www.w3.org/2001/XMLSchema#integer
}
}
**WHERE {
GRAPH http://uri.etsi.org/ngsi-ld/Entities {
urn:ngsi-ld:Vehicle:V123 http://uri.fiware.org/ns/datamodels/speed ?blank.
?blank http://uri.etsi.org/ngsi-ld/hasValue ?d
}
}**

Your update does not produce any affects as "?blank" and "?d" are not bounded. The URI format are also wrong (see the use of '<' and '>' for URIs)

**Comment by bliu92** [comment]
Thank you Luca. 
I just tested and it works. But still the URIs should be surrounded by the <>, otherwise it would not work.

**Comment by lroffia** [comment]
Good! Yes of course, SPARQL requires the URI to be represented in such a way.Inviato da smartphone Samsung Galaxy.
-------- Messaggio originale --------Da: Bang Liu <notifications@github.com> Data: 13/01/21  20:20  (GMT+01:00) A: arces-wot/SEPA <SEPA@noreply.github.com> Cc: Luca Roffia <lroffia@gmail.com>, Comment <comment@noreply.github.com> Oggetto: Re: [arces-wot/SEPA] General Question about the SPARQL UPDATE using DELETE Function. (#64) 
Thank you Luca.
I just tested and it works. But still the URIs should be surrounded by the <>, otherwise it would not work.

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/arces-wot/SEPA/issues/64#issuecomment-759663249",
"url": "https://github.com/arces-wot/SEPA/issues/64#issuecomment-759663249",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by bliu92** [comment]
> Good! Yes of course, SPARQL requires the URI to be represented in such a way.Inviato da smartphone Samsung Galaxy. -------- Messaggio originale --------Da: Bang Liu <notifications@github.com> Data: 13/01/21 20:20 (GMT+01:00) A: arces-wot/SEPA <SEPA@noreply.github.com> Cc: Luca Roffia <lroffia@gmail.com>, Comment <comment@noreply.github.com> Oggetto: Re: [arces-wot/SEPA] General Question about the SPARQL UPDATE using DELETE Function. (#64) Thank you Luca. I just tested and it works. But still the URIs should be surrounded by the <>, otherwise it would not work. —You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe. [ { "@context": "http://schema.org", "@type": "EmailMessage", "potentialAction": { "@type": "ViewAction", "target": "[#64 (comment)](https://github.com/arces-wot/SEPA/issues/64#issuecomment-759663249)", "url": "[#64 (comment)](https://github.com/arces-wot/SEPA/issues/64#issuecomment-759663249)", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { "@type": "Organization", "name": "GitHub", "url": "https://github.com" } } ]

Hallo Luca, can i ask you about another question about the deletion function ?

I ran the NGSI-LD Engine and use Post to create an entity. I use the code to get all triples from that entity. 

I can delete or change the value of attributes, however, when i try to delete the entity including all triples inside, it cannot delete all triples from that entity.

As i tried the following two methodes:

![image](https://user-images.githubusercontent.com/11669531/104635084-bb7a2600-56a1-11eb-90ff-a91b2faef48d.png)

This is the second Methode:
![image](https://user-images.githubusercontent.com/11669531/104635152-d0ef5000-56a1-11eb-9dff-b4fe1b299f2f.png)

The first method did not work at all while using the second method, it did some work, but still the entity exists. When i have a look at the SPARQL Update, since we have multiple blank nodes here, we can only use the DELETE primitives. 

Thank you in advance.
