### ISSUE TITLE
Add JMX configuration files + log4j2 to engine release 

### ISSUE THREAD

**Issue by lroffia** [arces-wot/SEPA#8]

**Comment by lroffia** [comment]
The broker release should also include the files to configure logging (log4j2) and to allow JMX access to the engine instance. How can we provide such files to the "end-user"?

**Comment by relu91** [comment]
>The broker release should also include the files to configure logging (log4j2) and to allow JMX access to the engine instance. How can we provide such files to the "end-user"?

Are those considerations still valid?

**Comment by relu91** [comment]
@lroffia I am closing the issue it seems that this consideration are not valid anymore.
